---
- name: "Creates backend app directory"
  file:
    path: ~/backend_app
    state: directory

- name: "UnArchive"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app
       

- name: "Install dependencies for project"
  shell: |
    cd ~/backend_app
    npm i

- name: "Executing node"
  shell: |
    cd ~/backend_app/dist
    pm2 stop default
    pm2 start -f main.js


  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu


